//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawhatNet.Study.RN42XVPTest.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrawhatNet.Study.RN42XVPTest.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutPageHeader_About {
            get {
                return ResourceManager.GetString("AboutPageHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutPageHeader_Credit {
            get {
                return ResourceManager.GetString("AboutPageHeader_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutPageHeader_Privacy {
            get {
                return ResourceManager.GetString("AboutPageHeader_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本ソフトウェアは、デザイン上の理由で一部英語表記を用いています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutText_Notice_English_Body {
            get {
                return ResourceManager.GetString("AboutText_Notice_English_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語表記について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutText_Notice_English_Header {
            get {
                return ResourceManager.GetString("AboutText_Notice_English_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本ソフトウェアはThe Noun Projectの成果物であるアイコンを利用しています。
        ///各アイコンはCreative Commons Attribution 3.0、もしくはパブリックドメインのライセンスで配布されています。
        /// - Map Marker(No.2846)はP.J. Onoriによるデザインです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutText_Notice_NounProject_Body {
            get {
                return ResourceManager.GetString("AboutText_Notice_NounProject_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Noun Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutText_Notice_NounProject_Header {
            get {
                return ResourceManager.GetString("AboutText_Notice_NounProject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニュー項目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vesion 1.0.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationRelease {
            get {
                return ResourceManager.GetString("ApplicationRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RN-42XVP Test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://app.strawhat.net/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationUrl {
            get {
                return ResourceManager.GetString("ApplicationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (c) 2014 nobukuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BTデバイス探索・接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_DevConectionPageTitle {
            get {
                return ResourceManager.GetString("Label_DevConectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RFCommでの通信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_MainPageTitle {
            get {
                return ResourceManager.GetString("Label_MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ja-jp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
